### ISSUE TITLE
Big Sprites no work

### ISSUE THREAD

**Issue by Xuande08** [sainteos/project-spero#15]
![image](https://cloud.githubusercontent.com/assets/12190877/9939587/b4bcb5fa-5d30-11e5-9674-7095713ca915.png)

Animated ones scale to 32X32 ( the one in the picture is supposed to be 64X64)
Non-Animated ones cut off and only show 1/4 of the sprite.

**Comment by sainteos** [comment]
Are you loading these as SpriteObject attachments when they do this?

**Comment by Xuande08** [comment]
It happens regardless
There are 3 watchers, the top left is non-animated and directly placed on the map,
the top right is animated and directly placed on the map
the bottom left is animated and loaded as a sprite object attached to Aidan.

**Comment by sainteos** [comment]
Everything seems to be the correct sizes now.
<img width="575" alt="screen shot 2015-09-17 at 11 08 37" src="https://cloud.githubusercontent.com/assets/13241909/9941823/a471885a-5d2c-11e5-97d5-e1ffe23abbbb.png">
